@endpoint = https://zi9b8xsi91.execute-api.eu-west-1.amazonaws.com/prod

# CREATE
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Rome",
    "comment": "Good Pizza"
}
###

# READ ALL
GET {{endpoint}}/spaces
###

# READ BY ID
GET {{endpoint}}/spaces?spaceId=895af759-a4a2-43fd-8715-7209b2ea6567
###

# READ BY LOCATION
GET {{endpoint}}/spaces?location=London
###

# UPDATE
PUT {{endpoint}}/spaces?spaceId=6a03bae8-480c-44ed-a5a0-619f2de45a9e
Content-Type: application/json

{
    "location": "Updated Location"
}
###

# DELETE
DELETE {{endpoint}}/spaces?spaceId=6a03bae8-480c-44ed-a5a0-619f2de45a9e
###