@endpoint = https://zi9b8xsi91.execute-api.eu-west-1.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=27ec7a05-6e03-4d38-8e5a-4954673143a1
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best location"
}
###